image: docker:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]

stages:
  - test
  - build

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

test_server:
  stage: test
  script:
    - docker build --target builder -t server-builder .
    - docker run server-builder cargo test --release -- --test-threads=1

build_client:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/client client/
    - docker push $CI_REGISTRY_IMAGE/client
  only:
    - master

build_server:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/server .
    - docker push $CI_REGISTRY_IMAGE/server
  only:
    - master