image: docker:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]

stages:
  - context
  - test
  - build

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

feed_repo_md:
  stage: context
  image: registry.semanticallyinvalid.net/utility/ftb:latest
  script:
    - feed_the_machine --include rs . > hyperchess.md
  artifacts:
    name: repo-md-$CI_COMMIT_SHA
    paths:
      - hyperchess.md
    when: always


test_server:
  stage: test
  script:
    - docker build --target builder -t server-builder .
    - docker run server-builder cargo test --release -- --test-threads=1

build_client:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/client client/
    - docker push $CI_REGISTRY_IMAGE/client
  only:
    - master

build_server:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/server .
    - docker push $CI_REGISTRY_IMAGE/server
  only:
    - master